# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates Auditory Nerve Images
#'
#' @param wav a sampled mono signal
#' @param inNumOfChannels is the number of channels for decimation
#' @param inFirstFreq frequency of first channel (in critical band units)
#' @param inFreqDist the frequency bandwidth of the "auditory filter"
#' @param inSampleFrequency is the sample frequency of the input signal
#' @return Auditory Image + additional files
ear_process <- function(wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency) {
    .Call(`_eaR_ear_process`, wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency)
}

